dist: bionic

language: rust

env:
 global:
   - RUST_BACKTRACE=1

rust:
  - stable

matrix:
  fast_finish: true

before_script:
  - echo "deb http://cz.archive.ubuntu.com/ubuntu disco main universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install cmake doxygen xdot
  - sudo apt-get install g++-multilib libc6-dev-i386 gcc-arm-none-eabi libnewlib-arm-none-eabi
  - rustup target add thumbv6m-none-eabi
  - rustup component add rustfmt

script:
  - cargo build
  - cargo build --example longfi
  - cargo build --example longfi --release
  - cargo fmt -- --check